// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    return $('form').submit(function() {
      $('input, textarea').each(function() {
        if ($(this).val() === '') {
          $(this).addClass('inputError');
          $(this).after('<span style="color: red">Os campos em vermelho s&atilde;o obrigat&oacute;rios.</span>');
        } else {
          return $(this).removeClass('inputError');
        }
      });
      if ($('input, textarea').hasClass('inputError')) {
        return false;
      } else {
        return true;
      }
    });
  });

}).call(this);
